### ISSUE TITLE
WebDebuff leaves stat drain after combat

### ISSUE THREAD

**Issue by Eragonx0852** [Ormael13/CoCX#131]
If the spooders plaster you with so much web that your speed sinks below 1 then you will be left with a stat drain after combat

If the total curse added during the fight takes your stat below 1, when combat ends it wont remove the full debuf, only the the positive section of the debuff...
e.g. if you have 130 spe and in a fight with a spider get hit by web attack (50 spe drained each), that will be [130 core, -150 bonus, 1 effective]
when combat ends the (-129) spe debuff that affects the stat wil be removed, leaving a (-21) spe stat drain that cannot be removed by ending combat

**Comment by Ormael13** [comment]
It should been fixed with web debuff been now working like curse than previous way.
