### ISSUE TITLE
Mysticality Ascension spell cost increase

### ISSUE THREAD

**Issue by Eragonx0852** [Ormael13/CoCX#132]
Mysticality Ascension perk seems to break spellcasting mana costs in ng+  and raise them far beyond what they should be and what they show up as costing when hovering over a spell in spellcasting menu

**Comment by Ormael13** [comment]
It only increase spell costs by up to 10% of perk spellpower increase that is max 300%. Well in any case made perk decresae costs by similary amount it increase it per rank (which would be ~1%).
