### ISSUE TITLE
Fix vag capacity not decreasing after transforming FROM a slime?

### ISSUE THREAD

**Issue by Svalkash** [Ormael13/CoCX#257]
> in the caves, beat a dark slime, and pick "letz rape" when you win. this will turn you completely int oa dark slime, includign a massive vag capacity. then just metamorph back to your prefered bod yconfiguration.

Maybe instead of giving +8000/+9000 to BonusVCapacity after transforming to Goo/Kitsune, it should change vagina TYPE instead?
And (for goo) just take it back after transforming back (when your body changes, you can't fit so much - goo, tails - kitsune)
It would make much more sense.

**Comment by gatogrande1987** [comment]
As I see, at what point do we pull the Bonus?
This could just be rolled into timechange, once decided

**Comment by Svalkash** [comment]
> at what point do we pull the Bonus?
Not sure if I understand correctly, but it can be tied to something special, like kitsune tails or goo lower body.
Well... ideally, we could cut away any BonusVCapacity changes and instead add the checks like
```as3
if (body == LowerBody.GOO) capacity += 9000;
```
directly to the function calculating your capacity. It also takes stuff like looseness into account.
