### ISSUE TITLE
Shields Don't Show on Char Viewer

### ISSUE THREAD

**Issue by pokepika01** [Ormael13/CoCX#503]
Only Sanctuary variants appear on the character viewer - I'm fairly sure it's down to an issue in the If statements in model.xml - Sanctuary(N) will show as a generic shield, but none of the others. Also, Dark Aegis shows as a generic shield due to the XML expecting PlayerHasSanctuary**Corrupt**, but CharViewContext is giving it PlayerHasSanctuary**Unholy**.

**Comment by LordShadeogorath** [comment]
This should now be fixed, and then some (I added more sprites to reflect shield size) in the master-wip branch
