### ISSUE TITLE
The Sing ability is completely overpowered

### ISSUE THREAD

**Issue by Gamerooni** [Ormael13/CoCX#674]
My level 64 character with 823 Int and max level Melkie lungs deals 343,198,112,597 damage from a single Sing -> Aria. It seems a bit much for an ability that doesn't seem to use any Mana or Fatigue.

I'd go in and adjust the scaling myself but unfortunately I'm not that familiar with the codebase.

**Comment by PrestonLaw** [comment]
Counterpoint - there are some fights where that isn't enough damage.  I've been playing new saves on Xianxia primary difficulty and Infernum secondary difficulty, and even going to depth 10 in the Ebon Labyrinth means the bosses suddenly have e14 health, and if you can't do 10 trillion damage per turn on average at that point, the boss is going to deal you enough lust dmg cherry taps to win before you kill it... that is, unless you have Eromancer Transference or bonkers-high max lust or something.

**Comment by Gamerooni** [comment]
alright, I'll take your word for it.
